CREATE TABLE IF NOT EXISTS BOOKMARK(
   ID IDENTITY NOT NULL PRIMARY KEY,
   NAME VARCHAR(500),
   URL VARCHAR(500),
   CREATEDATE DATE,
   MODIFYDATE DATE,
   FILENAME VARCHAR(50),
   classId INT,
   clicksNum BIGINT,
   LASTDATE DATE,
   ICON VARCHAR(2000)
);

CREATE TABLE IF NOT EXISTS BOOKMARKCLASS(
   ID IDENTITY NOT NULL PRIMARY KEY,
   CLASSNAME VARCHAR(500),
   CREATEDATE DATE,
   PARENTID INT
);